---
linters:
  enable-all: true
  disable:
    # it should improve to support more known patterns
    - varnamelen
    - nolintlint
    # deprecated linters
    - maligned
    - scopelint
    - golint
    - interfacer
