---
name: test
on:
  - push
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - uses: actions/setup-node@v3
      - run: |
          cd web/say-hello
          npm install
          npm run build
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: true
      - uses: actions/setup-node@v3
      - run: |
          cd web/say-hello
          npm install
          npm run build
      - run: go test -v ./... -covermode=atomic -coverprofile=coverage.out
      - uses: codecov/codecov-action@v1
        with:
          files: coverage.out
